databases:
  - id: postgres-test
    type: postgres
    name: PostgreSQL
    host: lineage-databases-test-database-1
    port: 5432
    user: postgres
    password: postgres
    db_name: healthcare
  - id: postgres-train
    type: postgres
    name: PostgreSQL train
    host: lineage-databases-model-train-database-1
    port: 5432
    user: postgres
    password: postgres
    db_name: online_store
  - id: sqlserver-lineage
    type: sqlserver
    name: SQL Server Lineage
    host: lineage-databases-sqlserver-1
    port: 1433
    user: SA
    password: Sqlserver123
    db_name: healthcare
  - id: oracle-lineage
    type: oracle
    name: Oracle Lineage
    host: lineage-databases-oracle-test-1
    port: 1521
    user: C##data_lineage
    password: Oracle123
    db_name: XE
