true_relationships = {
    # ('accounts', 'customers'): 1,
    # ('transactions', 'accounts'): 1,
    # ('invoices', 'customers'): 1,
    # ('payments', 'invoices'): 1,
    # ('salaries', 'employees'): 1,
    # ('budget_items', 'budget_categories'): 1,
    # ('credit_cards', 'customers'): 1,
    # ('credit_card_transactions', 'credit_cards'): 1,
    # ('loans', 'customers'): 1,
    # ('loan_payments', 'loans'): 1,
    # ('investments', 'customers'): 1,
    # ('investment_transactions', 'investments'): 1,
    # ('insurance_policies', 'customers'): 1,
    # ('insurance_claims', 'insurance_policies'): 1,
    # ('tax_returns', 'customers'): 1,
    # ('tax_payments', 'tax_returns'): 1,
    # ('vendor_payments', 'vendor_invoices'): 1,
    # ('employee_expenses', 'employees'): 1,
    # ('department_allocations', 'departments'): 1,
    # ('goal_tracker', 'financial_goals'): 1,
    # ('investment_opportunities', 'customers'): 1,
    # ('market_analysis', 'investment_opportunities'): 1,
    # ('portfolio_recommendations', 'customers'): 1,
    # ('financial_planning', 'employees'): 1,
    # ('tax_filing_status', 'customers'): 1,
    # ('insurance_coverage', 'insurance_policies'): 1,
    # ('vendor_services', 'vendor_invoices'): 1,
    # ('department_projects', 'departments'): 1,
    # ('employee_skills', 'employees'): 1,
    # ('customer_feedback', 'customers'): 1,
    # ('financial_advice', 'customers'): 1,
    # ('investment_premiums', 'insurance_policies'): 1,
    # ('loan_applications', 'customers'): 1,
    # ('loan_repayments', 'loan_applications'): 1,
    # ('tax_return_amendments', 'tax_returns'): 1,
    # ('investment_transactions_history', 'investment_opportunities'): 1,
    # ('employee_training', 'employee_skills'): 1,
    # ('customer_service_requests', 'customers'): 1,
    # ('financial_planning_goals', 'financial_planning'): 1,
    # ('insurance_policy_changes', 'insurance_policies'): 1,
    # ('vendor_service_requests', 'vendor_invoices'): 1,
    # ('employee_evaluation_results', 'employees'): 1,
    # ('investment_opportunity_assessments', 'investment_opportunities'): 1,
    # ('loan_offers', 'loan_applications'): 1,
    # ('investment_portfolios', 'customers'): 1,
    # ('investment_portfolio_updates', 'investment_portfolios'): 1,
    # ('employee_performance_ratings', 'employees'): 1,
    # ('customer_service_response_times', 'customer_service_requests'): 1,
    # ('financial_planning_goal_updates', 'financial_planning_goals'): 1,
    # ('insurance_policy_cancellations', 'insurance_policies'): 1,
    # ('vendor_service_request_statuses', 'vendor_service_requests'): 1,
    # ('employee_skill_level_updates', 'employee_skills'): 1,
    # ('investment_opportunity_assessment_results', 'investment_opportunity_assessments'): 1,
    # ('customer_preferences', 'customers'): 1,
    # ('customer_notifications', 'customers'): 1,
    # ('transaction_fees', 'transactions'): 1,
    # ('customer_addresses', 'customers'): 1,
    # ('customer_contacts', 'customers'): 1,
    # ('employee_shifts', 'employees'): 1,
    # ('department_heads', 'departments'): 1,
    # ('department_heads', 'employees'): 1,
    # ('customer_rewards', 'customers'): 1,
    # ('audit_trails', 'employees'): 1,
    # ('customer_relationship_manager', 'departments'): 1,
    # ('customer_relationship_manager', 'customers'): 1,
    # ('investment_opportunity_analysis_results', 'investment_opportunities'): 1,
    # ('investment_opportunity_analysis_results', 'employees'): 1,
    # ('financial_planning_goal_status_updates', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_status_updates', 'employees'): 1,
    # ('insurance_policy_coverage_updates', 'insurance_policies'): 1,
    # ('insurance_policy_coverage_updates', 'employees'): 1,
    # ('vendor_service_request_item', 'vendor_service_requests'): 1,
    # ('employee_performance_goals', 'employee_performance_ratings'): 1,
    # ('employee_performance_goals', 'employees'): 1,
    # ('investment_portfolio_assets', 'investment_portfolios'): 1,
    # ('customer_service_request_feedback', 'customer_service_requests'): 1,
    # ('customer_service_request_feedback', 'customers'): 1,
    # ('financial_planning_goal_categories', 'financial_planning_goals'): 1,
    # ('customer_loyalty', 'customers'): 1,
    # ('account_statements', 'accounts'): 1,
    # ('customer_promotions', 'customers'): 1,
    # ('customer_promotions', 'promotional_offers'): 1,
    # ('account_alerts', 'accounts'): 1,
    # ('customer_investment_advisors', 'customers'): 1,
    # ('customer_investment_advisors', 'investment_advisors'): 1,
    # ('financial_planning_sessions', 'customers'): 1,
    # ('campaign_customers', 'marketing_campaigns'): 1,
    # ('campaign_customers', 'customers'): 1,
    # ('audit_reports', 'regulatory_compliance'): 1,
    # ('internal_audits', 'departments'): 1,
    # ('customer_service_levels', 'customers'): 1,
    # ('customer_service_levels', 'service_levels'): 1,
    # ('insurance_policy_claims', 'insurance_policies'): 1,
    # ('insurance_policy_claims', 'employees'): 1,
    # ('investment_opportunity_recommendation', 'investment_opportunities'): 1,
    # ('investment_opportunity_recommendation', 'employees'): 1,
    # ('financial_planning_goal_priority', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_priority', 'employees'): 1,
    # ('employee_relationship_managers', 'employees'): 1,
    # ('customer_relationship_manager_feedback', 'employee_relationship_managers'): 1,
    # ('customer_relationship_manager_feedback', 'departments'): 1,
    # ('insurance_policy_coverage_type', 'insurance_policies'): 1,
    # ('investment_portfolio_asset_category', 'investment_portfolios'): 1,
    # ('financial_planning_goal_target_updates', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_target_updates', 'employees'): 1,
    # ('employee_performance_goal_category', 'employee_performance_goals'): 1,
    # ('asset_depreciation', 'asset_management'): 1,
    # ('customer_support_tickets', 'customers'): 1,
    # ('employee_attendance', 'employees'): 1,
    # ('employee_training_sessions', 'employees'): 1,
    # ('employee_training_sessions', 'training_programs'): 1,
    # ('marketing_campaign_metrics', 'marketing_campaigns'): 1,
    # ('customer_loyalty_rewards', 'customers'): 1,
    # ('regulatory_fines', 'regulatory_compliance'): 1,
    # ('project_management', 'departments'): 1,
    # ('project_tasks', 'project_management'): 1,
    # ('customer_segment_assignments', 'customers'): 1,
    # ('customer_segment_assignments', 'customer_segments'): 1,
    # ('investment_opportunity_rating', 'investment_opportunities'): 1,
    # ('investment_opportunity_rating', 'employees'): 1,
    # ('financial_planning_goal_status', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_status', 'employees'): 1,
    # ('insurance_policy_claim_status', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_status', 'employees'): 1,
    # ('customer_relationship_manager_eval', 'employee_relationship_managers'): 1,
    # ('customer_relationship_manager_eval', 'departments'): 1,
    # ('investment_portfolio_asset_value', 'investment_portfolio_assets'): 1,
    # ('investment_portfolio_asset_value', 'investment_portfolios'): 1,
    # ('customer_service_request_item', 'customer_service_requests'): 1,
    # ('investment_opportunity_analysis', 'investment_opportunities'): 1,
    # ('investment_opportunity_analysis', 'employees'): 1,
    # ('insurance_policy_claim_update', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_update', 'employees'): 1,
    # ('employee_performance_goal_update', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_update', 'employees'): 1,
    # ('project_budget_allocations', 'project_management'): 1,
    # ('department_expense_reports', 'departments'): 1,
    # ('inventory_transactions', 'product_inventory'): 1,
    # ('employee_leave_requests', 'employees'): 1,
    # ('customer_demographics', 'customers'): 1,
    # ('marketing_campaign_performance', 'marketing_campaigns'): 1,
    # ('partner_contracts', 'business_partners'): 1,
    # ('supplier_payments', 'supplier_invoices'): 1,
    # ('employee_work_hours', 'employees'): 1,
    # ('payroll', 'employees'): 1,
    # ('investment_risks', 'investments'): 1,
    # ('investment_risk_mitigation', 'investment_risks'): 1,
    # ('marketing_budget', 'marketing_campaigns'): 1,
    # ('product_sales', 'product_inventory'): 1,
    # ('customer_discounts', 'customers'): 1,
    # ('employee_bonuses', 'employees'): 1,
    # ('financial_planning_goal_action', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_action', 'employees'): 1,
    # ('investment_portfolio_asset_type', 'investment_portfolio_assets'): 1,
    # ('customer_relationship_manager_tasks', 'employee_relationship_managers'): 1,
    # ('customer_relationship_manager_tasks', 'departments'): 1,
    # ('insurance_policy_coverage_update', 'insurance_policies'): 1,
    # ('insurance_policy_coverage_update', 'employees'): 1,
    # ('financial_planning_goal_target', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_target', 'employees'): 1,
    # ('financial_planning_goal_category_update', 'financial_planning_goal_categories'): 1,
    # ('financial_planning_goal_category_update', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_value_update', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_item_update', 'customer_service_requests'): 1,
    # ('employee_performance_goal_action', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_action', 'employees'): 1,
    # ('insurance_policy_coverage_analysis', 'insurance_policies'): 1,
    # ('insurance_policy_coverage_analysis', 'employees'): 1,
    # ('financial_planning_goal_target_update', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_type_update', 'investment_portfolio_assets'): 1,
    # ('customer_relationship_manager_task_item', 'customer_relationship_manager_tasks'): 1,
    # ('customer_relationship_manager_task_item', 'employee_relationship_managers'): 1,
    # ('customer_relationship_manager_task_item', 'departments'): 1,
    # ('financial_planning_goal_category_item', 'financial_planning_goal_categories'): 1,
    # ('financial_planning_goal_category_item', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_holding_period', 'investment_portfolio_assets'): 1,
    # ('employee_performance_goal_metric', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_metric', 'employees'): 1,
    # ('insurance_policy_coverage_update_item', 'insurance_policies'): 1,
    # ('financial_planning_goal_target_item', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_target_item', 'employees'): 1,
    # ('customer_relationship_manager_task_item_update', 'customer_relationship_manager_tasks'): 1,
    # ('insurance_policy_claim_item_update', 'insurance_policy_claims'): 1,
    # ('financial_planning_goal_risk_assessment', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_risk_assessment', 'employees'): 1,
    # ('investment_portfolio_asset_diversification', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_category', 'customer_service_requests'): 1,
    # ('employee_performance_goal_incentive', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_incentive', 'employees'): 1,
    # ('insurance_policy_claim_resolution', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_resolution', 'employees'): 1,
    # ('financial_planning_goal_portfolio', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_portfolio', 'employees'): 1,
    # ('investment_portfolio_asset_liquidity', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_priority', 'customer_service_requests'): 1,
    # ('employee_performance_goal_kpi', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_kpi', 'employees'): 1,
    # ('financial_planning_goal_scrutiny', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_scrutiny', 'employees'): 1,
    # ('investment_portfolio_asset_maturity', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_frequency', 'customer_service_requests'): 1,
    # ('employee_performance_goal_milestone', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_milestone', 'employees'): 1,
    # ('insurance_policy_claim_payment', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_payment', 'employees'): 1,
    # ('financial_planning_goal_analysis', 'financial_planning_goals'): 1,
    # ('financial_planning_goal_analysis', 'employees'): 1,
    # ('investment_portfolio_asset_return', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_status', 'customer_service_requests'): 1,
    # ('employee_performance_goal_recognition', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_recognition', 'employees'): 1,
    # ('investment_portfolio_asset_valuation', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_classification', 'customer_service_requests'): 1,
    # ('employee_performance_goal_coaching', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_coaching', 'employees'): 1,
    # ('insurance_policy_claim_investigation', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_investigation', 'employees'): 1,
    # ('customer_service_request_attachment', 'customer_service_requests'): 1,
    # ('employee_performance_goal_innovation', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_innovation', 'employees'): 1,
    # ('insurance_policy_claim_dispute', 'insurance_policy_claims'): 1,
    # ('insurance_policy_claim_dispute', 'employees'): 1,
    # ('financial_planning_goal_stakeholder_analysis', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_hedging', 'investment_portfolio_assets'): 1,
    # ('employee_performance_goal_communication', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_communication', 'employees'): 1,
    # ('customer_service_request_follow_up', 'customer_service_requests'): 1,
    # ('financial_planning_goal_revenue_forecasting', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_collateralization', 'investment_portfolio_assets'): 1,
    # ('employee_performance_goal_quality_improvement', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_quality_improvement', 'employees'): 1,
    # ('financial_planning_goal_sustainability', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_rebalancing', 'investment_portfolio_assets'): 1,
    # ('employee_performance_goal_team_building', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_team_building', 'employees'): 1,
    # ('customer_service_request_workaround', 'customer_service_requests'): 1,
    # ('employee_performance_goal_delegation', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_delegation', 'employees'): 1,
    # ('financial_planning_goal_diversification', 'financial_planning_goals'): 1,
    # ('customer_service_request_triage', 'customer_service_requests'): 1,
    # ('employee_performance_goal_time_management', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_time_management', 'employees'): 1,
    # ('financial_planning_goal_inflation', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_yield', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_alert', 'customer_service_requests'): 1,
    # ('financial_planning_goal_liquidity', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_volatility', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_archive', 'customer_service_requests'): 1,
    # ('employee_performance_goal_prioritization', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_prioritization', 'employees'): 1,
    # ('financial_planning_goal_risk_management', 'financial_planning_goals'): 1,
    # ('investment_portfolio_asset_credit_rating', 'investment_portfolio_assets'): 1,
    # ('customer_service_request_dashboard', 'customer_service_requests'): 1,
    # ('employee_performance_goal_workload', 'employee_performance_goals'): 1,
    # ('employee_performance_goal_workload', 'employees'): 1,

    ('customers', 'customer_accounts_transactions'): 1,
    ('accounts', 'customer_accounts_transactions'): 1,
    ('transactions', 'customer_accounts_transactions'): 1,

    ('customers', 'customer_invoices_payments'): 1,
    ('invoices', 'customer_invoices_payments'): 1,
    ('payments', 'customer_invoices_payments'): 1,

    ('employees', 'employee_departments_salaries'): 1,
    ('departments', 'employee_departments_salaries'): 1,
    ('salaries', 'employee_departments_salaries'): 1,

    ('credit_cards', 'credit_card_transactions_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_customers'): 1,
    ('customers', 'credit_card_transactions_customers'): 1,

    ('loans', 'loan_payments_customers'): 1,
    ('loan_payments', 'loan_payments_customers'): 1,
    ('customers', 'loan_payments_customers'): 1,

    ('investments', 'investment_transactions_customers'): 1,
    ('investment_transactions', 'investment_transactions_customers'): 1,
    ('customers', 'investment_transactions_customers'): 1,

    ('insurance_policies', 'insurance_claims_customers'): 1,
    ('insurance_claims', 'insurance_claims_customers'): 1,
    ('customers', 'insurance_claims_customers'): 1,

    ('tax_returns', 'tax_payments_customers'): 1,
    ('tax_payments', 'tax_payments_customers'): 1,
    ('customers', 'tax_payments_customers'): 1,

    ('vendor_invoices', 'vendor_payments_departments'): 1,
    ('vendor_payments', 'vendor_payments_departments'): 1,
    ('departments', 'vendor_payments_departments'): 1,

    ('employee_expenses', 'employee_expenses_departments'): 1,
    ('employees', 'employee_expenses_departments'): 1,
    ('departments', 'employee_expenses_departments'): 1,

    ('department_allocations', 'department_allocations_employees'): 1,
    ('departments', 'department_allocations_employees'): 1,
    ('employees', 'department_allocations_employees'): 1,

    ('financial_reports', 'financial_reports_departments'): 1,
    ('budget_items', 'financial_reports_departments'): 1,
    ('departments', 'financial_reports_departments'): 1,

    ('financial_goals', 'financial_goals_employees'): 1,
    ('goal_tracker', 'financial_goals_employees'): 1,
    ('employees', 'financial_goals_employees'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_employees'): 1,
    ('customers', 'portfolio_recommendations_employees'): 1,
    ('employees', 'portfolio_recommendations_employees'): 1,

    ('financial_planning', 'financial_planning_departments'): 1,
    ('employees', 'financial_planning_departments'): 1,
    ('departments', 'financial_planning_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_returns'): 1,
    ('customers', 'tax_filing_status_returns'): 1,
    ('tax_returns', 'tax_filing_status_returns'): 1,

    ('insurance_coverage', 'insurance_coverage_customers'): 1,
    ('insurance_policies', 'insurance_coverage_customers'): 1,
    ('customers', 'insurance_coverage_customers'): 1,

    ('vendor_services', 'vendor_services_departments'): 1,
    ('vendor_invoices', 'vendor_services_departments'): 1,
    ('departments', 'vendor_services_departments'): 1,

    ('department_projects', 'department_projects_employees'): 1,
    ('departments', 'department_projects_employees'): 1,
    ('employees', 'department_projects_employees'): 1,

    ('customers', 'customer_credit_card_transactions'): 1,
    ('credit_cards', 'customer_credit_card_transactions'): 1,
    ('credit_card_transactions', 'customer_credit_card_transactions'): 1,

    ('employees', 'employee_salaries_departments'): 1,
    ('salaries', 'employee_salaries_departments'): 1,
    ('departments', 'employee_salaries_departments'): 1,

    ('accounts', 'account_transactions_customers'): 1,
    ('transactions', 'account_transactions_customers'): 1,
    ('customers', 'account_transactions_customers'): 1,

    ('loans', 'loan_due_payments_employees'): 1,
    ('loan_payments', 'loan_due_payments_employees'): 1,
    ('employees', 'loan_due_payments_employees'): 1,

    ('investment_opportunities', 'investment_transactions_opportunities_customers'): 1,
    ('investment_transactions', 'investment_transactions_opportunities_customers'): 1,
    ('customers', 'investment_transactions_opportunities_customers'): 1,

    ('insurance_policies', 'insurance_claims_departments'): 1,
    ('insurance_claims', 'insurance_claims_departments'): 1,
    ('custdepartmentsomers', 'insurance_claims_departments'): 1,

    ('tax_returns', 'tax_payments_employees'): 1,
    ('tax_payments', 'tax_payments_employees'): 1,
    ('employees', 'tax_payments_employees'): 1,

    ('vendor_invoices', 'vendor_due_payments_departments'): 1,
    ('vendor_payments', 'vendor_due_payments_departments'): 1,
    ('departments', 'vendor_due_payments_departments'): 1,

    ('employee_expenses', 'department_expenses_employees'): 1,
    ('departments', 'department_expenses_employees'): 1,
    ('employees', 'department_expenses_employees'): 1,

    ('financial_reports', 'financial_reports_departments_budgets'): 1,
    ('budget_categories', 'financial_reports_departments_budgets'): 1,
    ('departments', 'financial_reports_departments_budgets'): 1,

    ('financial_goals', 'financial_goals_departments'): 1,
    ('goal_tracker', 'financial_goals_departments'): 1,
    ('departments', 'financial_goals_departments'): 1,

    ('investment_opportunities', 'investment_opportunities_employees'): 1,
    ('investment_transactions', 'investment_opportunities_employees'): 1,
    ('employees', 'investment_opportunities_employees'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_departments'): 1,
    ('customers', 'portfolio_recommendations_departments'): 1,
    ('departments', 'portfolio_recommendations_departments'): 1,

    ('financial_planning', 'financial_planning_employees_departments'): 1,
    ('employees', 'financial_planning_employees_departments'): 1,
    ('departments', 'financial_planning_employees_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_customers_departments'): 1,
    ('customers', 'tax_filing_status_customers_departments'): 1,
    ('departments', 'tax_filing_status_customers_departments'): 1,

    ('insurance_coverage', 'insurance_policies_departments'): 1,
    ('insurance_policies', 'insurance_policies_departments'): 1,
    ('departments', 'insurance_policies_departments'): 1,

    ('vendor_services', 'vendor_services_invoices_departments'): 1,
    ('vendor_invoices', 'vendor_services_invoices_departments'): 1,
    ('departments', 'vendor_services_invoices_departments'): 1,

    ('custom', 'customer_feedback_employees'): 1,
    ('customers', 'customer_feedback_employees'): 1,
    ('employees', 'customer_feedback_employees'): 1,

    ('financial_advice', 'financial_advice_employees'): 1,
    ('customers', 'financial_advice_employees'): 1,
    ('employees', 'financial_advice_employees'): 1,

    ('investment_premiums', 'investment_premiums_departments'): 1,
    ('insurance_policies', 'investment_premiums_departments'): 1,
    ('departments', 'investment_premiums_departments'): 1,

    ('tax_return_amendments', 'tax_return_amendments_customers'): 1,
    ('tax_returns', 'tax_return_amendments_customers'): 1,
    ('customers', 'tax_return_amendments_customers'): 1,

    ('investment_transactions_history', 'investment_transactions_history_customers'): 1,
    ('investment_opportunities', 'investment_transactions_history_customers'): 1,
    ('customers', 'investment_transactions_history_customers'): 1,

    ('employee_training', 'employee_training_departments'): 1,
    ('employee_skills', 'employee_training_departments'): 1,
    ('departments', 'employee_training_departments'): 1,

    ('customer_service_requests', 'customer_service_requests_employees'): 1,
    ('customers', 'customer_service_requests_employees'): 1,
    ('employees', 'customer_service_requests_employees'): 1,

    ('financial_planning_goals', 'financial_planning_goals_employees'): 1,
    ('financial_planning', 'financial_planning_goals_employees'): 1,
    ('employees', 'financial_planning_goals_employees'): 1,

    ('insurance_policy_changes', 'insurance_policy_changes_departments'): 1,
    ('insurance_policies', 'insurance_policy_changes_departments'): 1,
    ('departments', 'insurance_policy_changes_departments'): 1,

    ('customers', 'customer_accounts_balance_transactions'): 1,
    ('accounts', 'customer_accounts_balance_transactions'): 1,
    ('transactions', 'customer_accounts_balance_transactions'): 1,

    ('customers', 'customer_invoices_paid_payments'): 1,
    ('invoices', 'customer_invoices_paid_payments'): 1,
    ('payments', 'customer_invoices_paid_payments'): 1,

    ('employees', 'employee_departments_hr_salaries'): 1,
    ('departments', 'employee_departments_hr_salaries'): 1,
    ('salaries', 'employee_departments_hr_salaries'): 1,

    ('credit_cards', 'credit_card_transactions_large_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_large_customers'): 1,
    ('customers', 'credit_card_transactions_large_customers'): 1,

    ('loans', 'loan_payments_large_customers'): 1,
    ('loan_payments', 'loan_payments_large_customers'): 1,
    ('customers', 'loan_payments_large_customers'): 1,

    ('investments', 'investment_transactions_large_customers'): 1,
    ('investment_transactions', 'investment_transactions_large_customers'): 1,
    ('customers', 'investment_transactions_large_customers'): 1,

    ('insurance_policies', 'insurance_claims_large_customers'): 1,
    ('insurance_claims', 'insurance_claims_large_customers'): 1,
    ('customers', 'insurance_claims_large_customers'): 1,

    ('vendor_invoices', 'vendor_payments_large_departments'): 1,
    ('vendor_payments', 'vendor_payments_large_departments'): 1,
    ('departments', 'vendor_payments_large_departments'): 1,

    ('employee_expenses', 'employee_expenses_large_departments'): 1,
    ('employees', 'employee_expenses_large_departments'): 1,
    ('departments', 'employee_expenses_large_departments'): 1,

    ('department_allocations', 'department_allocations_large_employees'): 1,
    ('departments', 'department_allocations_large_employees'): 1,
    ('employees', 'department_allocations_large_employees'): 1,

    ('financial_reports', 'financial_reports_large_departments'): 1,
    ('budget_items', 'financial_reports_large_departments'): 1,
    ('departments', 'financial_reports_large_departments'): 1,

    ('financial_goals', 'financial_goals_large_employees'): 1,
    ('goal_tracker', 'financial_goals_large_employees'): 1,
    ('employees', 'financial_goals_large_employees'): 1,

    ('investment_opportunities', 'investment_opportunities_large_customers'): 1,
    ('market_analysis', 'investment_opportunities_large_customers'): 1,
    ('customers', 'investment_opportunities_large_customers'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_large_departments'): 1,
    ('customers', 'portfolio_recommendations_large_departments'): 1,
    ('departments', 'portfolio_recommendations_large_departments'): 1,

    ('financial_planning', 'financial_planning_large_departments'): 1,
    ('employees', 'financial_planning_large_departments'): 1,
    ('departments', 'financial_planning_large_departments'): 1,

    ('insurance_coverage', 'insurance_policies_large_departments'): 1,
    ('insurance_policies', 'insurance_policies_large_departments'): 1,
    ('departments', 'insurance_policies_large_departments'): 1,

    ('vendor_services', 'vendor_services_large_departments'): 1,
    ('vendor_invoices', 'vendor_services_large_departments'): 1,
    ('departments', 'vendor_services_large_departments'): 1,

    ('customer_feedback', 'customer_feedback_recent_employees'): 1,
    ('customers', 'customer_feedback_recent_employees'): 1,
    ('employees', 'customer_feedback_recent_employees'): 1,

    ('financial_advice', 'financial_advice_recent_employees'): 1,
    ('customers', 'financial_advice_recent_employees'): 1,
    ('employees', 'financial_advice_recent_employees'): 1,

    ('investment_premiums', 'investment_premiums_recent_departments'): 1,
    ('insurance_policies', 'investment_premiums_recent_departments'): 1,
    ('departments', 'investment_premiums_recent_departments'): 1,

    ('tax_return_amendments', 'tax_return_amendments_recent_customers'): 1,
    ('tax_returns', 'tax_return_amendments_recent_customers'): 1,
    ('customers', 'tax_return_amendments_recent_customers'): 1,

    ('customer_service_requests', 'customer_service_requests_recent_employees'): 1,
    ('customers', 'customer_service_requests_recent_employees'): 1,
    ('employees', 'customer_service_requests_recent_employees'): 1,

    ('vendor_services', 'vendor_services_recent_large_departments'): 1,
    ('vendor_invoices', 'vendor_services_recent_large_departments'): 1,
    ('departments', 'vendor_services_recent_large_departments'): 1,

    ('insurance_coverage', 'insurance_policies_recent_large_departments'): 1,
    ('insurance_policies', 'insurance_policies_recent_large_departments'): 1,
    ('departments', 'insurance_policies_recent_large_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_recent_large_departments'): 1,
    ('customers', 'tax_filing_status_recent_large_departments'): 1,
    ('departments', 'tax_filing_status_recent_large_departments'): 1,

    ('financial_planning', 'financial_planning_recent_large_departments'): 1,
    ('employees', 'financial_planning_recent_large_departments'): 1,
    ('departments', 'financial_planning_recent_large_departments'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_recent_large_departments'): 1,
    ('customers', 'portfolio_recommendations_recent_large_departments'): 1,
    ('departments', 'portfolio_recommendations_recent_large_departments'): 1,

    ('investment_opportunities', 'investment_opportunities_recent_large_customers'): 1,
    ('market_analysis', 'investment_opportunities_recent_large_customers'): 1,
    ('customers', 'investment_opportunities_recent_large_customers'): 1,

    ('financial_goals', 'financial_goals_recent_large_employees'): 1,
    ('goal_tracker', 'financial_goals_recent_large_employees'): 1,
    ('employees', 'financial_goals_recent_large_employees'): 1,

    ('financial_reports', 'financial_reports_recent_large_departments'): 1,
    ('budget_items', 'financial_reports_recent_large_departments'): 1,
    ('departments', 'financial_reports_recent_large_departments'): 1,

    ('department_allocations', 'department_allocations_recent_large_employees'): 1,
    ('departments', 'department_allocations_recent_large_employees'): 1,
    ('employees', 'department_allocations_recent_large_employees'): 1,

    ('employee_expenses', 'employee_expenses_recent_large_departments'): 1,
    ('employees', 'employee_expenses_recent_large_departments'): 1,
    ('departments', 'employee_expenses_recent_large_departments'): 1,

    ('vendor_invoices', 'vendor_payments_recent_large_departments'): 1,
    ('vendor_payments', 'vendor_payments_recent_large_departments'): 1,
    ('departments', 'vendor_payments_recent_large_departments'): 1,

    ('tax_returns', 'tax_payments_recent_large_customers'): 1,
    ('tax_payments', 'tax_payments_recent_large_customers'): 1,
    ('customers', 'tax_payments_recent_large_customers'): 1,

    ('insurance_policies', 'insurance_claims_recent_large_customers'): 1,
    ('insurance_claims', 'insurance_claims_recent_large_customers'): 1,
    ('customers', 'insurance_claims_recent_large_customers'): 1,

    ('investments', 'investment_transactions_recent_large_customers'): 1,
    ('investment_transactions', 'investment_transactions_recent_large_customers'): 1,
    ('customers', 'investment_transactions_recent_large_customers'): 1,

    ('loans', 'loan_payments_recent_large_customers'): 1,
    ('loan_payments', 'loan_payments_recent_large_customers'): 1,
    ('customers', 'loan_payments_recent_large_customers'): 1,

    ('credit_cards', 'credit_card_transactions_recent_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_recent_customers'): 1,
    ('customers', 'credit_card_transactions_recent_customers'): 1,

    ('employees', 'employee_departments_recent_salaries'): 1,
    ('departments', 'employee_departments_recent_salaries'): 1,
    ('salaries', 'employee_departments_recent_salaries'): 1,

    ('customers', 'customer_invoices_recent_payments'): 1,
    ('invoices', 'customer_invoices_recent_payments'): 1,
    ('payments', 'customer_invoices_recent_payments'): 1,

    ('customers', 'customer_accounts_recent_transactions'): 1,
    ('accounts', 'customer_accounts_recent_transactions'): 1,
    ('transactions', 'customer_accounts_recent_transactions'): 1,

    ('insurance_policy_changes', 'insurance_policy_changes_recent_departments'): 1,
    ('insurance_policies', 'insurance_policy_changes_recent_departments'): 1,
    ('departments', 'insurance_policy_changes_recent_departments'): 1,

    ('financial_planning_goals', 'financial_planning_goals_recent_employees'): 1,
    ('financial_planning', 'financial_planning_goals_recent_employees'): 1,
    ('employees', 'financial_planning_goals_recent_employees'): 1,

    ('employee_training', 'employee_training_recent_departments'): 1,
    ('employee_skills', 'employee_training_recent_departments'): 1,
    ('departments', 'employee_training_recent_departments'): 1,

    ('investment_transactions_history', 'investment_transactions_history_recent_customers'): 1,
    ('investment_opportunities', 'investment_transactions_history_recent_customers'): 1,
    ('customers', 'investment_transactions_history_recent_customers'): 1,

    ('department_projects', 'department_projects_large_employees'): 1,
    ('departments', 'department_projects_large_employees'): 1,
    ('employees', 'department_projects_large_employees'): 1,

    ('customers', 'tax_filing_status_large_departments'): 1,
    ('tax_filing_status', 'tax_filing_status_large_departments'): 1,
    ('departments', 'tax_filing_status_large_departments'): 1,

    ('account_alerts', 'customer_account_alerts_view'): 1,
    ('accounts', 'customer_account_alerts_view'): 1,
    ('customers', 'customer_account_alerts_view'): 1,
    ('account_statements', 'customer_account_statements_view'): 1,
    ('accounts', 'customer_account_statements_view'): 1,
    ('customers', 'customer_account_statements_view'): 1,
    ('accounts', 'customer_accounts_view'): 1,
    ('customers', 'customer_accounts_view'): 1,
    ('credit_card_transactions', 'customer_credit_card_transactions_view'): 1,
    ('credit_cards', 'customer_credit_card_transactions_view'): 1,
    ('customers', 'customer_credit_card_transactions_view'): 1,
    ('credit_cards', 'customer_credit_cards_view'): 1,
    ('customers', 'customer_credit_cards_view'): 1,
    ('customer_demographics', 'customer_demographics_view'): 1,
    ('customers', 'customer_demographics_view'): 1,
    ('customer_feedback', 'customer_feedback_view'): 1,
    ('customers', 'customer_feedback_view'): 1,
    ('customers', 'customer_financial_advice_view'): 1,
    ('financial_advice', 'customer_financial_advice_view'): 1,
    ('customers', 'customer_financial_planning_sessions_view'): 1,
    ('financial_planning_sessions', 'customer_financial_planning_sessions_view'): 1,
    ('customers', 'customer_insurance_claims_view'): 1,
    ('insurance_claims', 'customer_insurance_claims_view'): 1,
    ('insurance_policies', 'customer_insurance_claims_view'): 1,
    ('customers', 'customer_insurance_policies_view'): 1,
    ('insurance_policies', 'customer_insurance_policies_view'): 1,
    ('customer_investment_advisors', 'customer_investment_advisors_view'): 1,
    ('customers', 'customer_investment_advisors_view'): 1,
    ('investment_advisors', 'customer_investment_advisors_view'): 1,
    ('customers', 'customer_investment_opportunities_view'): 1,
    ('investment_opportunities', 'customer_investment_opportunities_view'): 1,
    ('customers', 'customer_investment_portfolios_view'): 1,
    ('investment_portfolios', 'customer_investment_portfolios_view'): 1,
    ('customers', 'customer_investment_transactions_view'): 1,
    ('investment_transactions', 'customer_investment_transactions_view'): 1,
    ('investments', 'customer_investment_transactions_view'): 1,
    ('customers', 'customer_investments_transactions_view'): 1,
    ('investment_transactions', 'customer_investments_transactions_view'): 1,
    ('investments', 'customer_investments_transactions_view'): 1,
    ('customers', 'customer_investments_view'): 1,
    ('investments', 'customer_investments_view'): 1,
    ('customers', 'customer_invoices_view'): 1,
    ('invoices', 'customer_invoices_view'): 1,
    ('customers', 'customer_loan_payments_view'): 1,
    ('loan_payments', 'customer_loan_payments_view'): 1,
    ('loans', 'customer_loan_payments_view'): 1,
    ('customers', 'customer_loans_payments_view'): 1,
    ('loan_payments', 'customer_loans_payments_view'): 1,
    ('loans', 'customer_loans_payments_view'): 1,
    ('customers', 'customer_loans_view'): 1,
    ('loans', 'customer_loans_view'): 1,
    ('customer_loyalty', 'customer_loyalty_points_view'): 1,
    ('customers', 'customer_loyalty_points_view'): 1,
    ('customer_loyalty_rewards', 'customer_loyalty_rewards_view'): 1,
    ('customers', 'customer_loyalty_rewards_view'): 1,
    ('customers', 'customer_market_analysis_view'): 1,
    ('investment_opportunities', 'customer_market_analysis_view'): 1,
    ('market_analysis', 'customer_market_analysis_view'): 1,
    ('customers', 'customer_payments_view'): 1,
    ('invoices', 'customer_payments_view'): 1,
    ('payments', 'customer_payments_view'): 1,
    ('customers', 'customer_portfolio_assets_view'): 1,
    ('investment_portfolio_assets', 'customer_portfolio_assets_view'): 1,
    ('investment_portfolios', 'customer_portfolio_assets_view'): 1,
    ('customer_promotions', 'customer_promotional_offers_view'): 1,
    ('customers', 'customer_promotional_offers_view'): 1,
    ('promotional_offers', 'customer_promotional_offers_view'): 1,
    ('customer_relationship_manager', 'customer_relationship_managers_view'): 1,
    ('customers', 'customer_relationship_managers_view'): 1,
    ('customer_service_levels', 'customer_service_levels_view'): 1,
    ('customers', 'customer_service_levels_view'): 1,
    ('service_levels', 'customer_service_levels_view'): 1,
    ('customer_service_request_feedback', 'customer_service_requests_feedback_view'): 1,
    ('customer_service_requests', 'customer_service_requests_feedback_view'): 1,
    ('customers', 'customer_service_requests_feedback_view'): 1,
    ('customer_service_requests', 'customer_service_requests_view'): 1,
    ('customers', 'customer_service_requests_view'): 1,
    ('customers', 'customer_tax_payments_view'): 1,
    ('tax_payments', 'customer_tax_payments_view'): 1,
    ('tax_returns', 'customer_tax_payments_view'): 1,
    ('customers', 'customer_tax_return_amendments_view'): 1,
    ('tax_return_amendments', 'customer_tax_return_amendments_view'): 1,
    ('tax_returns', 'customer_tax_return_amendments_view'): 1,
    ('customers', 'customer_tax_returns_view'): 1,
    ('tax_returns', 'customer_tax_returns_view'): 1,
    ('accounts', 'customer_transactions_view'): 1,
    ('customers', 'customer_transactions_view'): 1,
    ('transactions', 'customer_transactions_view'): 1,
    ('department_allocations', 'department_allocations_view'): 1,
    ('departments', 'department_allocations_view'): 1,
    ('departments', 'department_internal_audits_view'): 1,
    ('internal_audits', 'department_internal_audits_view'): 1,
    ('departments', 'department_project_tasks_view'): 1,
    ('project_management', 'department_project_tasks_view'): 1,
    ('project_tasks', 'department_project_tasks_view'): 1,
    ('departments', 'department_projects_budgets_view'): 1,
    ('project_budget_allocations', 'department_projects_budgets_view'): 1,
    ('project_management', 'department_projects_budgets_view'): 1,
    ('department_projects', 'department_projects_view'): 1,
    ('departments', 'department_projects_view'): 1,
    ('employee_attendance', 'employee_attendance_view'): 1,
    ('employees', 'employee_attendance_view'): 1,
    ('employee_bonuses', 'employee_bonuses_view'): 1,
    ('employees', 'employee_bonuses_view'): 1,
    ('employee_evaluation_results', 'employee_evaluations_view'): 1,
    ('employees', 'employee_evaluations_view'): 1,
    ('employee_expenses', 'employee_expenses_view'): 1,
    ('employees', 'employee_expenses_view'): 1,
    ('employee_leave_requests', 'employee_leave_requests_view'): 1,
    ('employees', 'employee_leave_requests_view'): 1,
    ('employee_performance_goal_action', 'employee_performance_goals_actions_view'): 1,
    ('employee_performance_goals', 'employee_performance_goals_actions_view'): 1,
    ('employees', 'employee_performance_goals_actions_view'): 1,
    ('employee_performance_goals', 'employee_performance_goals_view'): 1,
    ('employees', 'employee_performance_goals_view'): 1,
    ('employee_performance_ratings', 'employee_performance_ratings_view'): 1,
    ('employees', 'employee_performance_ratings_view'): 1,
    ('employees', 'employee_salaries_view'): 1,
    ('salaries', 'employee_salaries_view'): 1,
    ('employee_shifts', 'employee_shift_schedules_view'): 1,
    ('employees', 'employee_shift_schedules_view'): 1,
    ('employee_skills', 'employee_skills_training_view'): 1,
    ('employee_training', 'employee_skills_training_view'): 1,
    ('employees', 'employee_skills_training_view'): 1,
    ('employee_skills', 'employee_skills_view'): 1,
    ('employees', 'employee_skills_view'): 1,
    ('employee_skills', 'employee_training_sessions_view'): 1,
    ('employee_training', 'employee_training_sessions_view'): 1,
    ('employees', 'employee_training_sessions_view'): 1,
}