version: "3.8"

name: lineage-databases

services:
  model-train-database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_store
    ports:
      - "5433:5432"
    volumes:
      - ./model-train-database-init.sql:/docker-entrypoint-initdb.d/init.sql

  test-database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    ports:
      - "5434:5432"
    volumes:
      - ./test-database-init.sql:/docker-entrypoint-initdb.d/init.sql

  sqlserver:
    build: ./SQLServer
    environment:
      SA_PASSWORD: "Sqlserver123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

