true_relationships = {
    ('customers', 'customer_accounts_transactions'): 1,
    ('accounts', 'customer_accounts_transactions'): 1,
    ('transactions', 'customer_accounts_transactions'): 1,

    ('customers', 'customer_invoices_payments'): 1,
    ('invoices', 'customer_invoices_payments'): 1,
    ('payments', 'customer_invoices_payments'): 1,

    ('employees', 'employee_departments_salaries'): 1,
    ('departments', 'employee_departments_salaries'): 1,
    ('salaries', 'employee_departments_salaries'): 1,

    ('credit_cards', 'credit_card_transactions_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_customers'): 1,
    ('customers', 'credit_card_transactions_customers'): 1,

    ('loans', 'loan_payments_customers'): 1,
    ('loan_payments', 'loan_payments_customers'): 1,
    ('customers', 'loan_payments_customers'): 1,

    ('investments', 'investment_transactions_customers'): 1,
    ('investment_transactions', 'investment_transactions_customers'): 1,
    ('customers', 'investment_transactions_customers'): 1,

    ('insurance_policies', 'insurance_claims_customers'): 1,
    ('insurance_claims', 'insurance_claims_customers'): 1,
    ('customers', 'insurance_claims_customers'): 1,

    ('tax_returns', 'tax_payments_customers'): 1,
    ('tax_payments', 'tax_payments_customers'): 1,
    ('customers', 'tax_payments_customers'): 1,

    ('vendor_invoices', 'vendor_payments_departments'): 1,
    ('vendor_payments', 'vendor_payments_departments'): 1,
    ('departments', 'vendor_payments_departments'): 1,

    ('employee_expenses', 'employee_expenses_departments'): 1,
    ('employees', 'employee_expenses_departments'): 1,
    ('departments', 'employee_expenses_departments'): 1,

    ('department_allocations', 'department_allocations_employees'): 1,
    ('departments', 'department_allocations_employees'): 1,
    ('employees', 'department_allocations_employees'): 1,

    ('financial_reports', 'financial_reports_departments'): 1,
    ('budget_items', 'financial_reports_departments'): 1,
    ('departments', 'financial_reports_departments'): 1,

    ('financial_goals', 'financial_goals_employees'): 1,
    ('goal_tracker', 'financial_goals_employees'): 1,
    ('employees', 'financial_goals_employees'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_employees'): 1,
    ('customers', 'portfolio_recommendations_employees'): 1,
    ('employees', 'portfolio_recommendations_employees'): 1,

    ('financial_planning', 'financial_planning_departments'): 1,
    ('employees', 'financial_planning_departments'): 1,
    ('departments', 'financial_planning_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_returns'): 1,
    ('customers', 'tax_filing_status_returns'): 1,
    ('tax_returns', 'tax_filing_status_returns'): 1,

    ('insurance_coverage', 'insurance_coverage_customers'): 1,
    ('insurance_policies', 'insurance_coverage_customers'): 1,
    ('customers', 'insurance_coverage_customers'): 1,

    ('vendor_services', 'vendor_services_departments'): 1,
    ('vendor_invoices', 'vendor_services_departments'): 1,
    ('departments', 'vendor_services_departments'): 1,

    ('department_projects', 'department_projects_employees'): 1,
    ('departments', 'department_projects_employees'): 1,
    ('employees', 'department_projects_employees'): 1,

    ('customers', 'customer_credit_card_transactions'): 1,
    ('credit_cards', 'customer_credit_card_transactions'): 1,
    ('credit_card_transactions', 'customer_credit_card_transactions'): 1,

    ('employees', 'employee_salaries_departments'): 1,
    ('salaries', 'employee_salaries_departments'): 1,
    ('departments', 'employee_salaries_departments'): 1,

    ('accounts', 'account_transactions_customers'): 1,
    ('transactions', 'account_transactions_customers'): 1,
    ('customers', 'account_transactions_customers'): 1,

    ('loans', 'loan_due_payments_employees'): 1,
    ('loan_payments', 'loan_due_payments_employees'): 1,
    ('employees', 'loan_due_payments_employees'): 1,

    ('investment_opportunities', 'investment_transactions_opportunities_customers'): 1,
    ('investment_transactions', 'investment_transactions_opportunities_customers'): 1,
    ('customers', 'investment_transactions_opportunities_customers'): 1,

    ('insurance_policies', 'insurance_claims_departments'): 1,
    ('insurance_claims', 'insurance_claims_departments'): 1,
    ('custdepartmentsomers', 'insurance_claims_departments'): 1,

    ('tax_returns', 'tax_payments_employees'): 1,
    ('tax_payments', 'tax_payments_employees'): 1,
    ('employees', 'tax_payments_employees'): 1,

    ('vendor_invoices', 'vendor_due_payments_departments'): 1,
    ('vendor_payments', 'vendor_due_payments_departments'): 1,
    ('departments', 'vendor_due_payments_departments'): 1,

    ('employee_expenses', 'department_expenses_employees'): 1,
    ('departments', 'department_expenses_employees'): 1,
    ('employees', 'department_expenses_employees'): 1,

    ('financial_reports', 'financial_reports_departments_budgets'): 1,
    ('budget_categories', 'financial_reports_departments_budgets'): 1,
    ('departments', 'financial_reports_departments_budgets'): 1,

    ('financial_goals', 'financial_goals_departments'): 1,
    ('goal_tracker', 'financial_goals_departments'): 1,
    ('departments', 'financial_goals_departments'): 1,

    ('investment_opportunities', 'investment_opportunities_employees'): 1,
    ('investment_transactions', 'investment_opportunities_employees'): 1,
    ('employees', 'investment_opportunities_employees'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_departments'): 1,
    ('customers', 'portfolio_recommendations_departments'): 1,
    ('departments', 'portfolio_recommendations_departments'): 1,

    ('financial_planning', 'financial_planning_employees_departments'): 1,
    ('employees', 'financial_planning_employees_departments'): 1,
    ('departments', 'financial_planning_employees_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_customers_departments'): 1,
    ('customers', 'tax_filing_status_customers_departments'): 1,
    ('departments', 'tax_filing_status_customers_departments'): 1,

    ('insurance_coverage', 'insurance_policies_departments'): 1,
    ('insurance_policies', 'insurance_policies_departments'): 1,
    ('departments', 'insurance_policies_departments'): 1,

    ('vendor_services', 'vendor_services_invoices_departments'): 1,
    ('vendor_invoices', 'vendor_services_invoices_departments'): 1,
    ('departments', 'vendor_services_invoices_departments'): 1,

    ('custom', 'customer_feedback_employees'): 1,
    ('customers', 'customer_feedback_employees'): 1,
    ('employees', 'customer_feedback_employees'): 1,

    ('financial_advice', 'financial_advice_employees'): 1,
    ('customers', 'financial_advice_employees'): 1,
    ('employees', 'financial_advice_employees'): 1,

    ('investment_premiums', 'investment_premiums_departments'): 1,
    ('insurance_policies', 'investment_premiums_departments'): 1,
    ('departments', 'investment_premiums_departments'): 1,

    ('tax_return_amendments', 'tax_return_amendments_customers'): 1,
    ('tax_returns', 'tax_return_amendments_customers'): 1,
    ('customers', 'tax_return_amendments_customers'): 1,

    ('investment_transactions_history', 'investment_transactions_history_customers'): 1,
    ('investment_opportunities', 'investment_transactions_history_customers'): 1,
    ('customers', 'investment_transactions_history_customers'): 1,

    ('employee_training', 'employee_training_departments'): 1,
    ('employee_skills', 'employee_training_departments'): 1,
    ('departments', 'employee_training_departments'): 1,

    ('customer_service_requests', 'customer_service_requests_employees'): 1,
    ('customers', 'customer_service_requests_employees'): 1,
    ('employees', 'customer_service_requests_employees'): 1,

    ('financial_planning_goals', 'financial_planning_goals_employees'): 1,
    ('financial_planning', 'financial_planning_goals_employees'): 1,
    ('employees', 'financial_planning_goals_employees'): 1,

    ('insurance_policy_changes', 'insurance_policy_changes_departments'): 1,
    ('insurance_policies', 'insurance_policy_changes_departments'): 1,
    ('departments', 'insurance_policy_changes_departments'): 1,

    ('customers', 'customer_accounts_balance_transactions'): 1,
    ('accounts', 'customer_accounts_balance_transactions'): 1,
    ('transactions', 'customer_accounts_balance_transactions'): 1,

    ('customers', 'customer_invoices_paid_payments'): 1,
    ('invoices', 'customer_invoices_paid_payments'): 1,
    ('payments', 'customer_invoices_paid_payments'): 1,

    ('employees', 'employee_departments_hr_salaries'): 1,
    ('departments', 'employee_departments_hr_salaries'): 1,
    ('salaries', 'employee_departments_hr_salaries'): 1,

    ('credit_cards', 'credit_card_transactions_large_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_large_customers'): 1,
    ('customers', 'credit_card_transactions_large_customers'): 1,

    ('loans', 'loan_payments_large_customers'): 1,
    ('loan_payments', 'loan_payments_large_customers'): 1,
    ('customers', 'loan_payments_large_customers'): 1,

    ('investments', 'investment_transactions_large_customers'): 1,
    ('investment_transactions', 'investment_transactions_large_customers'): 1,
    ('customers', 'investment_transactions_large_customers'): 1,

    ('insurance_policies', 'insurance_claims_large_customers'): 1,
    ('insurance_claims', 'insurance_claims_large_customers'): 1,
    ('customers', 'insurance_claims_large_customers'): 1,

    ('vendor_invoices', 'vendor_payments_large_departments'): 1,
    ('vendor_payments', 'vendor_payments_large_departments'): 1,
    ('departments', 'vendor_payments_large_departments'): 1,

    ('employee_expenses', 'employee_expenses_large_departments'): 1,
    ('employees', 'employee_expenses_large_departments'): 1,
    ('departments', 'employee_expenses_large_departments'): 1,

    ('department_allocations', 'department_allocations_large_employees'): 1,
    ('departments', 'department_allocations_large_employees'): 1,
    ('employees', 'department_allocations_large_employees'): 1,

    ('financial_reports', 'financial_reports_large_departments'): 1,
    ('budget_items', 'financial_reports_large_departments'): 1,
    ('departments', 'financial_reports_large_departments'): 1,

    ('financial_goals', 'financial_goals_large_employees'): 1,
    ('goal_tracker', 'financial_goals_large_employees'): 1,
    ('employees', 'financial_goals_large_employees'): 1,

    ('investment_opportunities', 'investment_opportunities_large_customers'): 1,
    ('market_analysis', 'investment_opportunities_large_customers'): 1,
    ('customers', 'investment_opportunities_large_customers'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_large_departments'): 1,
    ('customers', 'portfolio_recommendations_large_departments'): 1,
    ('departments', 'portfolio_recommendations_large_departments'): 1,

    ('financial_planning', 'financial_planning_large_departments'): 1,
    ('employees', 'financial_planning_large_departments'): 1,
    ('departments', 'financial_planning_large_departments'): 1,

    ('insurance_coverage', 'insurance_policies_large_departments'): 1,
    ('insurance_policies', 'insurance_policies_large_departments'): 1,
    ('departments', 'insurance_policies_large_departments'): 1,

    ('vendor_services', 'vendor_services_large_departments'): 1,
    ('vendor_invoices', 'vendor_services_large_departments'): 1,
    ('departments', 'vendor_services_large_departments'): 1,

    ('customer_feedback', 'customer_feedback_recent_employees'): 1,
    ('customers', 'customer_feedback_recent_employees'): 1,
    ('employees', 'customer_feedback_recent_employees'): 1,

    ('financial_advice', 'financial_advice_recent_employees'): 1,
    ('customers', 'financial_advice_recent_employees'): 1,
    ('employees', 'financial_advice_recent_employees'): 1,

    ('investment_premiums', 'investment_premiums_recent_departments'): 1,
    ('insurance_policies', 'investment_premiums_recent_departments'): 1,
    ('departments', 'investment_premiums_recent_departments'): 1,

    ('tax_return_amendments', 'tax_return_amendments_recent_customers'): 1,
    ('tax_returns', 'tax_return_amendments_recent_customers'): 1,
    ('customers', 'tax_return_amendments_recent_customers'): 1,

    ('customer_service_requests', 'customer_service_requests_recent_employees'): 1,
    ('customers', 'customer_service_requests_recent_employees'): 1,
    ('employees', 'customer_service_requests_recent_employees'): 1,

    ('vendor_services', 'vendor_services_recent_large_departments'): 1,
    ('vendor_invoices', 'vendor_services_recent_large_departments'): 1,
    ('departments', 'vendor_services_recent_large_departments'): 1,

    ('insurance_coverage', 'insurance_policies_recent_large_departments'): 1,
    ('insurance_policies', 'insurance_policies_recent_large_departments'): 1,
    ('departments', 'insurance_policies_recent_large_departments'): 1,

    ('tax_filing_status', 'tax_filing_status_recent_large_departments'): 1,
    ('customers', 'tax_filing_status_recent_large_departments'): 1,
    ('departments', 'tax_filing_status_recent_large_departments'): 1,

    ('financial_planning', 'financial_planning_recent_large_departments'): 1,
    ('employees', 'financial_planning_recent_large_departments'): 1,
    ('departments', 'financial_planning_recent_large_departments'): 1,

    ('portfolio_recommendations', 'portfolio_recommendations_recent_large_departments'): 1,
    ('customers', 'portfolio_recommendations_recent_large_departments'): 1,
    ('departments', 'portfolio_recommendations_recent_large_departments'): 1,

    ('investment_opportunities', 'investment_opportunities_recent_large_customers'): 1,
    ('market_analysis', 'investment_opportunities_recent_large_customers'): 1,
    ('customers', 'investment_opportunities_recent_large_customers'): 1,

    ('financial_goals', 'financial_goals_recent_large_employees'): 1,
    ('goal_tracker', 'financial_goals_recent_large_employees'): 1,
    ('employees', 'financial_goals_recent_large_employees'): 1,

    ('financial_reports', 'financial_reports_recent_large_departments'): 1,
    ('budget_items', 'financial_reports_recent_large_departments'): 1,
    ('departments', 'financial_reports_recent_large_departments'): 1,

    ('department_allocations', 'department_allocations_recent_large_employees'): 1,
    ('departments', 'department_allocations_recent_large_employees'): 1,
    ('employees', 'department_allocations_recent_large_employees'): 1,

    ('employee_expenses', 'employee_expenses_recent_large_departments'): 1,
    ('employees', 'employee_expenses_recent_large_departments'): 1,
    ('departments', 'employee_expenses_recent_large_departments'): 1,

    ('vendor_invoices', 'vendor_payments_recent_large_departments'): 1,
    ('vendor_payments', 'vendor_payments_recent_large_departments'): 1,
    ('departments', 'vendor_payments_recent_large_departments'): 1,

    ('tax_returns', 'tax_payments_recent_large_customers'): 1,
    ('tax_payments', 'tax_payments_recent_large_customers'): 1,
    ('customers', 'tax_payments_recent_large_customers'): 1,

    ('insurance_policies', 'insurance_claims_recent_large_customers'): 1,
    ('insurance_claims', 'insurance_claims_recent_large_customers'): 1,
    ('customers', 'insurance_claims_recent_large_customers'): 1,

    ('investments', 'investment_transactions_recent_large_customers'): 1,
    ('investment_transactions', 'investment_transactions_recent_large_customers'): 1,
    ('customers', 'investment_transactions_recent_large_customers'): 1,

    ('loans', 'loan_payments_recent_large_customers'): 1,
    ('loan_payments', 'loan_payments_recent_large_customers'): 1,
    ('customers', 'loan_payments_recent_large_customers'): 1,

    ('credit_cards', 'credit_card_transactions_recent_customers'): 1,
    ('credit_card_transactions', 'credit_card_transactions_recent_customers'): 1,
    ('customers', 'credit_card_transactions_recent_customers'): 1,

    ('employees', 'employee_departments_recent_salaries'): 1,
    ('departments', 'employee_departments_recent_salaries'): 1,
    ('salaries', 'employee_departments_recent_salaries'): 1,

    ('customers', 'customer_invoices_recent_payments'): 1,
    ('invoices', 'customer_invoices_recent_payments'): 1,
    ('payments', 'customer_invoices_recent_payments'): 1,

    ('customers', 'customer_accounts_recent_transactions'): 1,
    ('accounts', 'customer_accounts_recent_transactions'): 1,
    ('transactions', 'customer_accounts_recent_transactions'): 1,

    ('insurance_policy_changes', 'insurance_policy_changes_recent_departments'): 1,
    ('insurance_policies', 'insurance_policy_changes_recent_departments'): 1,
    ('departments', 'insurance_policy_changes_recent_departments'): 1,

    ('financial_planning_goals', 'financial_planning_goals_recent_employees'): 1,
    ('financial_planning', 'financial_planning_goals_recent_employees'): 1,
    ('employees', 'financial_planning_goals_recent_employees'): 1,

    ('employee_training', 'employee_training_recent_departments'): 1,
    ('employee_skills', 'employee_training_recent_departments'): 1,
    ('departments', 'employee_training_recent_departments'): 1,

    ('investment_transactions_history', 'investment_transactions_history_recent_customers'): 1,
    ('investment_opportunities', 'investment_transactions_history_recent_customers'): 1,
    ('customers', 'investment_transactions_history_recent_customers'): 1,

    ('department_projects', 'department_projects_large_employees'): 1,
    ('departments', 'department_projects_large_employees'): 1,
    ('employees', 'department_projects_large_employees'): 1,

    ('customers', 'tax_filing_status_large_departments'): 1,
    ('tax_filing_status', 'tax_filing_status_large_departments'): 1,
    ('departments', 'tax_filing_status_large_departments'): 1,

    ('account_alerts', 'customer_account_alerts_view'): 1,
    ('accounts', 'customer_account_alerts_view'): 1,
    ('customers', 'customer_account_alerts_view'): 1,
    ('account_statements', 'customer_account_statements_view'): 1,
    ('accounts', 'customer_account_statements_view'): 1,
    ('customers', 'customer_account_statements_view'): 1,
    ('accounts', 'customer_accounts_view'): 1,
    ('customers', 'customer_accounts_view'): 1,
    ('credit_card_transactions', 'customer_credit_card_transactions_view'): 1,
    ('credit_cards', 'customer_credit_card_transactions_view'): 1,
    ('customers', 'customer_credit_card_transactions_view'): 1,
    ('credit_cards', 'customer_credit_cards_view'): 1,
    ('customers', 'customer_credit_cards_view'): 1,
    ('customer_demographics', 'customer_demographics_view'): 1,
    ('customers', 'customer_demographics_view'): 1,
    ('customer_feedback', 'customer_feedback_view'): 1,
    ('customers', 'customer_feedback_view'): 1,
    ('customers', 'customer_financial_advice_view'): 1,
    ('financial_advice', 'customer_financial_advice_view'): 1,
    ('customers', 'customer_financial_planning_sessions_view'): 1,
    ('financial_planning_sessions', 'customer_financial_planning_sessions_view'): 1,
    ('customers', 'customer_insurance_claims_view'): 1,
    ('insurance_claims', 'customer_insurance_claims_view'): 1,
    ('insurance_policies', 'customer_insurance_claims_view'): 1,
    ('customers', 'customer_insurance_policies_view'): 1,
    ('insurance_policies', 'customer_insurance_policies_view'): 1,
    ('customer_investment_advisors', 'customer_investment_advisors_view'): 1,
    ('customers', 'customer_investment_advisors_view'): 1,
    ('investment_advisors', 'customer_investment_advisors_view'): 1,
    ('customers', 'customer_investment_opportunities_view'): 1,
    ('investment_opportunities', 'customer_investment_opportunities_view'): 1,
    ('customers', 'customer_investment_portfolios_view'): 1,
    ('investment_portfolios', 'customer_investment_portfolios_view'): 1,
    ('customers', 'customer_investment_transactions_view'): 1,
    ('investment_transactions', 'customer_investment_transactions_view'): 1,
    ('investments', 'customer_investment_transactions_view'): 1,
    ('customers', 'customer_investments_transactions_view'): 1,
    ('investment_transactions', 'customer_investments_transactions_view'): 1,
    ('investments', 'customer_investments_transactions_view'): 1,
    ('customers', 'customer_investments_view'): 1,
    ('investments', 'customer_investments_view'): 1,
    ('customers', 'customer_invoices_view'): 1,
    ('invoices', 'customer_invoices_view'): 1,
    ('customers', 'customer_loan_payments_view'): 1,
    ('loan_payments', 'customer_loan_payments_view'): 1,
    ('loans', 'customer_loan_payments_view'): 1,
    ('customers', 'customer_loans_payments_view'): 1,
    ('loan_payments', 'customer_loans_payments_view'): 1,
    ('loans', 'customer_loans_payments_view'): 1,
    ('customers', 'customer_loans_view'): 1,
    ('loans', 'customer_loans_view'): 1,
    ('customer_loyalty', 'customer_loyalty_points_view'): 1,
    ('customers', 'customer_loyalty_points_view'): 1,
    ('customer_loyalty_rewards', 'customer_loyalty_rewards_view'): 1,
    ('customers', 'customer_loyalty_rewards_view'): 1,
    ('customers', 'customer_market_analysis_view'): 1,
    ('investment_opportunities', 'customer_market_analysis_view'): 1,
    ('market_analysis', 'customer_market_analysis_view'): 1,
    ('customers', 'customer_payments_view'): 1,
    ('invoices', 'customer_payments_view'): 1,
    ('payments', 'customer_payments_view'): 1,
    ('customers', 'customer_portfolio_assets_view'): 1,
    ('investment_portfolio_assets', 'customer_portfolio_assets_view'): 1,
    ('investment_portfolios', 'customer_portfolio_assets_view'): 1,
    ('customer_promotions', 'customer_promotional_offers_view'): 1,
    ('customers', 'customer_promotional_offers_view'): 1,
    ('promotional_offers', 'customer_promotional_offers_view'): 1,
    ('customer_relationship_manager', 'customer_relationship_managers_view'): 1,
    ('customers', 'customer_relationship_managers_view'): 1,
    ('customer_service_levels', 'customer_service_levels_view'): 1,
    ('customers', 'customer_service_levels_view'): 1,
    ('service_levels', 'customer_service_levels_view'): 1,
    ('customer_service_request_feedback', 'customer_service_requests_feedback_view'): 1,
    ('customer_service_requests', 'customer_service_requests_feedback_view'): 1,
    ('customers', 'customer_service_requests_feedback_view'): 1,
    ('customer_service_requests', 'customer_service_requests_view'): 1,
    ('customers', 'customer_service_requests_view'): 1,
    ('customers', 'customer_tax_payments_view'): 1,
    ('tax_payments', 'customer_tax_payments_view'): 1,
    ('tax_returns', 'customer_tax_payments_view'): 1,
    ('customers', 'customer_tax_return_amendments_view'): 1,
    ('tax_return_amendments', 'customer_tax_return_amendments_view'): 1,
    ('tax_returns', 'customer_tax_return_amendments_view'): 1,
    ('customers', 'customer_tax_returns_view'): 1,
    ('tax_returns', 'customer_tax_returns_view'): 1,
    ('accounts', 'customer_transactions_view'): 1,
    ('customers', 'customer_transactions_view'): 1,
    ('transactions', 'customer_transactions_view'): 1,
    ('department_allocations', 'department_allocations_view'): 1,
    ('departments', 'department_allocations_view'): 1,
    ('departments', 'department_internal_audits_view'): 1,
    ('internal_audits', 'department_internal_audits_view'): 1,
    ('departments', 'department_project_tasks_view'): 1,
    ('project_management', 'department_project_tasks_view'): 1,
    ('project_tasks', 'department_project_tasks_view'): 1,
    ('departments', 'department_projects_budgets_view'): 1,
    ('project_budget_allocations', 'department_projects_budgets_view'): 1,
    ('project_management', 'department_projects_budgets_view'): 1,
    ('department_projects', 'department_projects_view'): 1,
    ('departments', 'department_projects_view'): 1,
    ('employee_attendance', 'employee_attendance_view'): 1,
    ('employees', 'employee_attendance_view'): 1,
    ('employee_bonuses', 'employee_bonuses_view'): 1,
    ('employees', 'employee_bonuses_view'): 1,
    ('employee_evaluation_results', 'employee_evaluations_view'): 1,
    ('employees', 'employee_evaluations_view'): 1,
    ('employee_expenses', 'employee_expenses_view'): 1,
    ('employees', 'employee_expenses_view'): 1,
    ('employee_leave_requests', 'employee_leave_requests_view'): 1,
    ('employees', 'employee_leave_requests_view'): 1,
    ('employee_performance_goal_action', 'employee_performance_goals_actions_view'): 1,
    ('employee_performance_goals', 'employee_performance_goals_actions_view'): 1,
    ('employees', 'employee_performance_goals_actions_view'): 1,
    ('employee_performance_goals', 'employee_performance_goals_view'): 1,
    ('employees', 'employee_performance_goals_view'): 1,
    ('employee_performance_ratings', 'employee_performance_ratings_view'): 1,
    ('employees', 'employee_performance_ratings_view'): 1,
    ('employees', 'employee_salaries_view'): 1,
    ('salaries', 'employee_salaries_view'): 1,
    ('employee_shifts', 'employee_shift_schedules_view'): 1,
    ('employees', 'employee_shift_schedules_view'): 1,
    ('employee_skills', 'employee_skills_training_view'): 1,
    ('employee_training', 'employee_skills_training_view'): 1,
    ('employees', 'employee_skills_training_view'): 1,
    ('employee_skills', 'employee_skills_view'): 1,
    ('employees', 'employee_skills_view'): 1,
    ('employee_skills', 'employee_training_sessions_view'): 1,
    ('employee_training', 'employee_training_sessions_view'): 1,
    ('employees', 'employee_training_sessions_view'): 1,
}